### ISSUE TITLE
Cannot parse bonds of .out file

### ISSUE THREAD

**Issue by MDAddario** [ekwan/cctk#1]
For all of my .out files, the parser raises a ValueError when it tries to parse the bonds. Here is my rough duplicate of the stack trace:

line 304 of `cctk\gaussian_file.py`
```
bonds = parse.read_bonds(lines)
```
line 174 of `cctk\parse_gaussian.py`
```
raise ValueError(f"can't parse line {i} for bonding!")
```

The parser is getting stuck on the first line of `lines` in the output section, which is
```
 ! X1    R(1,-1)                 0.9015         Frozen                          !
```

I am not sure if the error is due to `parse.read_bonds(lines)` being called for the wrong section of lines in the output file, or that is not the case, that the given bonding type is not supported by the parser. Any help is appreciated.

**Comment by ekwan** [comment]
Hi Michael,

Thanks for reaching out.  We are looking into the problem and will get back to you soon.  Could you please provide some testing code and a sample file (assuming none of that is confidential)?  That will help us troubleshoot.

Best,
-Eugene

**Comment by MDAddario** [comment]
I'm sorry but I cannot include a sample .out file. However, the code that I followed was exactly the quick start guide. The runs were done using --Link1--, do you know if that might be responsible here?

**Comment by ekwan** [comment]
Could you possibly make a very simple Gaussian output file that will cause the same error?  What is X1?  Is that a dummy atom?

**Comment by MDAddario** [comment]
The problem was solved by trimming the header through removing everything before the line
```
Copyright (c) 1988-2019, Gaussian, Inc.  All Rights Reserved.
```
Unsure why, but I hope that provides some insight.

**Comment by ekwan** [comment]
That's really surprising!  Does this happen for every file you're running?  Which version of Gaussian are you using?

**Comment by MDAddario** [comment]
Its an issue for all of the Link1 jobs. I am on version 16

**Comment by ekwan** [comment]
Thanks.  Unforunately, we're not seeing the same thing here.  Could you please setup a very simple Link1 job that fails the parser and send it to us?  We'll take a look at it right away.

**Comment by MDAddario** [comment]
I'm sorry but I don't think I'll be able to send a sample. I've been told that I'm not allowed to release any of the output files, so I'll try to request one that is eligible for disclosure.

**Comment by corinwagen** [comment]
Hey Michael,

Any update on this? We'd love to help.

Corin
